'use client';
 import { useEffect, useMemo, useState } from 'react';

type Node = { id:string; label:string; kind:string; status:string; x:number; y:number; detail:string; error?:string };
type Task = { id:string; title:string; goal:string; status:string; progress:number; nodes:Node[]; edges:string[][]; artifacts:unknown[] };
type TimelineEvent = { id:number; phase:string; title:string; detail:string; state:'done'|'active'|'idle'|'error'; time:string };

const seedEvents: TimelineEvent[] = [
 {id:1,phase:'01',title:'识别研究意图',detail:'bulk RNA-seq · 处理组 vs 对照组 · 候选基因',state:'done',time:'0.3s'},
 {id:2,phase:'02',title:'重写分析问题',detail:'物种=人类 · 交付物=可发表结果',state:'done',time:'0.5s'},
 {id:3,phase:'03',title:'检索与证据重排',detail:'项目文件 2 · 技能包 3 · 文献 12',state:'active',time:'1.2s'},
 {id:4,phase:'04',title:'绑定分析依据',detail:'DESeq2 参数已绑定 4 条证据',state:'idle',time:'—'},
];

const clarificationQuestions = [
 {key:'format',number:'01',label:'数据格式',description:'决定从原始读段、比对结果还是计数矩阵开始。',options:[['Count 矩阵','直接进入 DESeq2，适合当前演示'],['FASTQ 文件','增加质控、比对和定量步骤'],['公共数据库','从 GEO / SRA 获取数据']]},
 {key:'comparison',number:'02',label:'比较方案',description:'决定设计矩阵、对比项和统计模型。',options:[['处理组 vs 对照组','单一对比，路径最清晰'],['多组比较','生成多个 contrasts'],['时间序列','使用时间效应模型']]},
 {key:'organism',number:'03',label:'研究物种',description:'决定参考基因组与基因注释版本。',options:[['人类','GRCh38 / GENCODE'],['小鼠','GRCm39 / GENCODE'],['大鼠','mRatBN7.2 / Ensembl']]},
 {key:'deliverable',number:'04',label:'交付物',description:'决定图表、表格和报告的完整程度。',options:[['探索性分析','快速结果与火山图'],['可发表结果','补充 QC、热图和方法说明'],['完整科研报告','输出图表、代码与报告']]},
] as const;

export default function Home() {
 const [authed,setAuthed]=useState(false); const [task,setTask]=useState<Task|null>(null); const [events,setEvents]=useState(seedEvents); const [liveLogs,setLiveLogs]=useState<string[]>([]); const [selected,setSelected]=useState('design'); const [tab,setTab]=useState<'todo'|'results'|'compute'|'notes'|'evidence'|'logs'|'code'|'structure'>('todo'); const [mobilePanel,setMobilePanel]=useState(false); const [messageText,setMessageText]=useState(''); const [sentMessages,setSentMessages]=useState<string[]>([]); const [agentReplies,setAgentReplies]=useState<string[]>([]); const [running,setRunning]=useState(false); const [retrying,setRetrying]=useState(false); const [answers,setAnswers]=useState({format:'',comparison:'',organism:'',deliverable:''}); const [codeText,setCodeText]=useState(''); const [sidebarWidth,setSidebarWidth]=useState(260); const [inspectorWidth,setInspectorWidth]=useState(320); const [evidenceHeight,setEvidenceHeight]=useState(92); const [resizing,setResizing]=useState<'sidebar'|'inspector'|'evidence'|null>(null); const [structureAngle,setStructureAngle]=useState(18); const [selectedResidue,setSelectedResidue]=useState<number|null>(null); const [draggingStructure,setDraggingStructure]=useState(false); const [viewportWidth,setViewportWidth]=useState(1440); const [planOpen,setPlanOpen]=useState(false); const [traceOpen,setTraceOpen]=useState(false); const [activeQuestion,setActiveQuestion]=useState(0); const [canvasZoom,setCanvasZoom]=useState(1); const [connectingFrom,setConnectingFrom]=useState<string|null>(null); const [extraEdges,setExtraEdges]=useState<string[][]>([]); const [canvasPan,setCanvasPan]=useState({x:0,y:0}); const [nodePositions,setNodePositions]=useState<Record<string,{x:number;y:number}>>({});
 useEffect(()=>{const syncViewport=()=>setViewportWidth(window.innerWidth); syncViewport(); window.addEventListener('resize',syncViewport); return()=>window.removeEventListener('resize',syncViewport)},[]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMobilePanel(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{ (async()=>{ const login=await fetch('/api/auth/login',{method:'POST'}); if(login.ok){setAuthed(true); const r=await fetch('/api/tasks'); const d=await r.json(); setTask(d.task);} })(); },[]);
 useEffect(()=>{ if(!authed||!task)return; const sync=()=>fetch('/api/tasks').then(r=>r.ok?r.json():null).then(d=>d&&setTask(d.task)); const es=new EventSource('/api/runs/run_demo_001/events'); es.onmessage=(message)=>{try{const e=JSON.parse(message.data);setLiveLogs(logs=>[...logs,`[${new Date(e.createdAt).toLocaleTimeString()}] ${e.type}${e.nodeId?` · ${e.nodeId}`:''}`].slice(-100));if(e.type==='code.delta'&&typeof e.payload?.text==='string')setCodeText(v=>v+e.payload.text);const map:any={ 'intent.detected':{id:1,state:'done',detail:'bulk RNA-seq · treated vs control',time:'0.3s'},'retrieval.started':{id:3,state:'active',detail:'正在检索项目文件、Skills 与文献',time:'…'},'retrieval.hit':{id:3,state:'active',detail:`项目文件 ${e.payload?.projectFiles||2} · Skills ${e.payload?.skills||3} · 文献 ${e.payload?.literature||12}`,time:'1.2s'},'evidence.reranked':{id:3,state:'done',detail:`保留 ${e.payload?.kept||4} 条高相关证据`,time:'1.8s'},'grounding.bound':{id:4,state:'done',detail:'参数已绑定证据，可进入执行',time:'2.1s'}};if(map[e.type])setEvents(items=>items.map(item=>item.id===map[e.type].id?{...item,...map[e.type]}:item));}catch{} sync();}; es.onerror=()=>{es.close();}; return ()=>es.close(); },[authed]);
 useEffect(()=>{ if(tab!=='structure') return; const canvas=document.querySelector<HTMLElement>('.structure-canvas'); if(!canvas)return; let down=false,lastX=0; const move=(e:PointerEvent)=>{if(!down)return; setStructureAngle(a=>a+(e.clientX-lastX)*.7); lastX=e.clientX}; const start=(e:PointerEvent)=>{down=true;lastX=e.clientX;canvas.setPointerCapture?.(e.pointerId)}; const end=()=>{down=false}; canvas.addEventListener('pointerdown',start); canvas.addEventListener('pointermove',move); canvas.addEventListener('pointerup',end); canvas.addEventListener('pointerleave',end); return()=>{canvas.removeEventListener('pointerdown',start);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',end);canvas.removeEventListener('pointerleave',end)} },[tab]);
 useEffect(()=>{ const canvas=document.querySelector<HTMLElement>('.structure-canvas'); if(canvas){ canvas.style.setProperty('--structure-angle',`${structureAngle}deg`); canvas.style.setProperty('--structure-shift',`${Math.sin(structureAngle/28)*18}px`); } },[structureAngle,tab]);
 useEffect(()=>{ if(tab!=='structure')return; const canvas=document.querySelector<HTMLElement>('.structure-canvas'); if(!canvas)return; const click=(e:MouseEvent)=>{const target=(e.target as HTMLElement).closest('.residue'); if(target){const n=Number([...target.classList].find(c=>/^r\d+$/.test(c))?.slice(1)); if(n){setSelectedResidue(n); canvas.querySelectorAll('.residue').forEach(el=>el.classList.toggle('chosen',el===target))}}}; canvas.addEventListener('click',click); return()=>canvas.removeEventListener('click',click)},[tab]);
 const node=useMemo(()=>task?.nodes.find(n=>n.id===selected),[task,selected]);
 const submitClarifications=async()=>{if(Object.values(answers).some(v=>!v))return;const r=await fetch('/api/tasks/task_demo_rnaseq/clarifications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({answers})});if(r.ok)setTask((await r.json()).task)};
 const approvePlan=async()=>{const r=await fetch('/api/workflows/workflow_demo/approve',{method:'POST'});if(r.ok)setTask((await r.json()).task)};
 const runDemo=async()=>{if(running||task?.status==='awaiting_approval'||task?.status==='clarifying')return;setRunning(true);await fetch('/api/runs',{method:'POST'});setTimeout(()=>setRunning(false),1800)};
    {task?.status==='clarifying'&&<div className="gate-card clarification-card"><div className="gate-head"><div><small>智能体需要补充信息</small><h2>先确认这次实验的分析上下文</h2><p>每项选择都会实时影响后续分析路径。</p></div><span className="gate-progress">已完成 {Object.values(answers).filter(Boolean).length} / 4</span></div><div className="question-nav">{clarificationQuestions.map((q,i)=><button key={q.key} className={`${activeQuestion===i?'active':''} ${answers[q.key]?'answered':''}`} onClick={()=>setActiveQuestion(i)}><span>{answers[q.key]?'✓':q.number}</span>{q.label}</button>)}</div>{clarificationQuestions.map((q,i)=>activeQuestion===i&&<section className="question-panel" key={q.key}><div className="question-copy"><small>{q.number} / 04</small><h3>{q.label}</h3><p>{q.description}</p></div><div className="option-cards">{q.options.map(([value,hint])=><button key={value} className={answers[q.key]===value?'selected':''} onClick={()=>{setAnswers(a=>({...a,[q.key]:value}));if(i<3)setTimeout(()=>setActiveQuestion(i+1),180)}}><i>{answers[q.key]===value?'●':'○'}</i><span><b>{value}</b><small>{hint}</small></span></button>)}</div></section>)}<div className="clarification-actions"><span>{Object.values(answers).filter(Boolean).length<4?'完成全部选择后生成计划':'上下文已完整，可以生成分析计划'}</span><button className="primary" onClick={submitClarifications} disabled={Object.values(answers).some(v=>!v)}>生成分析计划 →</button></div></div>}
 const retry=async()=>{setRetrying(true); setCodeText(''); await fetch('/api/runs/run_demo_001/nodes/design/retry',{method:'POST'}); setTimeout(()=>setRetrying(false),1300)};
 const sendMessage=()=>{const text=messageText.trim();if(!text)return;setSentMessages(items=>[...items,text]);setMessageText('');setTimeout(()=>setAgentReplies(items=>[...items,'已收到你的问题。我会结合当前项目文件和分析上下文，给出下一步可执行建议。']),220)};
 const cancel=async()=>{await fetch('/api/runs/run_demo_001/cancel',{method:'POST'}); const r=await fetch('/api/tasks'); if(r.ok)setTask((await r.json()).task)};
 const startResize=(kind:'sidebar'|'inspector'|'evidence',event:React.PointerEvent)=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);setResizing(kind);const startX=event.clientX,startY=event.clientY,base=kind==='sidebar'?sidebarWidth:kind==='inspector'?inspectorWidth:evidenceHeight;const move=(e:PointerEvent)=>{if(kind==='sidebar')setSidebarWidth(Math.min(390,Math.max(210,base+e.clientX-startX)));if(kind==='inspector')setInspectorWidth(Math.min(520,Math.max(260,base+startX-e.clientX)));if(kind==='evidence')setEvidenceHeight(Math.min(220,Math.max(70,base+e.clientY-startY)))};const up=()=>{setResizing(null);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};
 const clampZoom=(value:number)=>Math.min(1.6,Math.max(.55,value));
 const startCanvasPan=(event:React.PointerEvent<HTMLDivElement>)=>{if(event.target!==event.currentTarget)return;event.preventDefault();const start={x:event.clientX,y:event.clientY},base={...canvasPan};const move=(e:PointerEvent)=>setCanvasPan({x:base.x+e.clientX-start.x,y:base.y+e.clientY-start.y});const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};
 const startNodeDrag=(node:Node,event:React.PointerEvent<HTMLButtonElement>)=>{event.preventDefault();event.stopPropagation();if(event.shiftKey){if(connectingFrom&&connectingFrom!==node.id){setExtraEdges(items=>[...items,[connectingFrom,node.id]]);setConnectingFrom(null)}else setConnectingFrom(node.id);return}setSelected(node.id);const origin=nodePositions[node.id]||{x:node.x,y:node.y};const start={x:event.clientX,y:event.clientY};let moved=false;const move=(e:PointerEvent)=>{moved=true;setNodePositions(items=>({...items,[node.id]:{x:Math.max(0,origin.x+(e.clientX-start.x)/canvasZoom),y:Math.max(0,origin.y+(e.clientY-start.y)/canvasZoom)}}))};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(!moved){setTab('evidence');setMobilePanel(true)}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)};
 const resetCanvas=()=>{setCanvasZoom(1);setCanvasPan({x:0,y:0});setNodePositions({})};
 if(!authed||!task) return <main className="boot"><div className="boot-mark">◌</div><p>Initializing secure research workspace…</p></main>;
 return <main className={`app-shell ${resizing?'is-resizing':''}`} style={{gridTemplateColumns:`68px ${viewportWidth<=1500?Math.min(sidebarWidth,220):sidebarWidth}px minmax(0,1fr)`}}>
   <aside className="rail"><div className="brand">⦿</div><button className="rail-btn active">⌘<span>工作台</span></button><button className="rail-btn">◇<span>能力中心</span></button><button className="rail-btn">◈<span>文件</span></button><div className="rail-spacer"/><div className="avatar">DF</div></aside>
   <aside className="task-sidebar"><div className="project-head"><div><small>项目</small><strong>BioFlow 生命科学实验室</strong></div><span>⌄</span></div><div className="side-title"><span>任务 <em>3</em></span><button>＋ 新建任务</button></div><div className="task-item selected"><i className="dot yellow"/><div><b>{task.title}</b><small>运行中 · 42%</small></div></div><div className="task-item"><i className="dot blue"/><div><b>文献证据图谱</b><small>已完成 · 2 小时前</small></div></div><div className="task-item"><i className="dot gray"/><div><b>蛋白质结构预览</b><small>草稿 · 昨天</small></div></div><div className="side-divider"/><div className="side-title"><span>数据集</span><button>＋ 上传</button></div><div className="dataset"><span className="file-icon">CSV</span><div><b>counts.csv</b><small>2.4 MB · 24 个样本</small></div></div><div className="dataset"><span className="file-icon">TSV</span><div><b>sample_metadata.tsv</b><small>12 KB · schema 已校验</small></div></div><div className="sidebar-note">⌁ 云端计算会在你离开页面后继续运行。</div><div className="vertical-splitter left" onPointerDown={e=>startResize('sidebar',e)} title="拖拽调整任务栏宽度"/></aside>
   <section className="workspace"><header className="topbar"><div className="crumb"><span>快捷任务</span><b>/</b><strong>{task.title}</strong></div><div className="top-actions"><span className="live"><i/> 智能体运行 39 秒</span><button>分享</button><button>布局</button></div></header>
    <div className="goal-strip"><div><small>当前研究目标 · 生物信息学</small><h1>{task.goal}</h1></div><div className="goal-actions"><span className={`status-pill ${task.status}`}>● {task.status==='running'?'运行中':task.status==='clarifying'?'待补充信息':task.status==='awaiting_approval'?'待审批':task.status==='succeeded'?'已完成':task.status==='cancelled'?'已取消':task.status.toUpperCase()}</span><button className="secondary" onClick={()=>setPlanOpen(v=>!v)}>{planOpen?'收起计划':'分析计划'}</button><button className="secondary" onClick={()=>setMobilePanel(!mobilePanel)}>工具</button>{task.status==='running'&&<button className="secondary danger" onClick={cancel}>取消</button>}<button className="primary" onClick={runDemo}>{running?'运行中…':'运行工作流'}</button></div></div>
    <div className="dialogue-thread"><div className="user-message"><small>你 · 刚刚</small><p>我有 RNA-seq 数据，希望比较处理组与对照组，找出显著差异基因并生成火山图。</p></div><div className="agent-message"><div className="assistant-avatar">✦</div><div><small>BioFlow 智能体</small><p>可以。我会先检查项目文件，再确认数据格式、实验设计和交付要求，然后生成一份可审批的分析计划。</p><button className="trace-chip" onClick={()=>setTraceOpen(v=>!v)}>{traceOpen?'收起执行轨迹':'✓ 已检查项目文件 · 查看执行轨迹'}</button></div></div></div>
    <div className={`evidence-strip ${traceOpen?'':'trace-collapsed'}`} style={{height:evidenceHeight}}><div className="evidence-label"><span>✦</span><b>证据流水线</b><small>智能体决策追踪</small></div>{events.map(e=><div key={e.id} className={`evidence-step ${e.state}`} onClick={()=>setTab('evidence')}><span className="phase">{e.phase}</span><div><b>{e.title}</b><small>{e.detail}</small></div><em>{e.time}</em></div>)}<div className="horizontal-splitter" onPointerDown={e=>startResize('evidence',e)} title="拖拽调整证据区高度"/></div>
    {task?.status==='clarifying'&&<div className="gate-card clarification-card"><div className="gate-head"><div><small>智能体需要补充信息</small><h2>先确认这次实验的分析上下文</h2><p>每项选择都会实时影响后续分析路径。</p></div><span className="gate-progress">已完成 {Object.values(answers).filter(Boolean).length} / 4</span></div><div className="question-nav">{clarificationQuestions.map((q,i)=><button key={q.key} className={`${activeQuestion===i?'active':''} ${answers[q.key]?'answered':''}`} onClick={()=>setActiveQuestion(i)}><span>{answers[q.key]?'✓':q.number}</span>{q.label}</button>)}</div>{clarificationQuestions.map((q,i)=>activeQuestion===i&&<section className="question-panel" key={q.key}><div className="question-copy"><small>{q.number} / 04</small><h3>{q.label}</h3><p>{q.description}</p></div><div className="option-cards">{q.options.map(([value,hint])=><button key={value} className={answers[q.key]===value?'selected':''} onClick={()=>{setAnswers(a=>({...a,[q.key]:value}));if(i<3)setTimeout(()=>setActiveQuestion(i+1),180)}}><i>{answers[q.key]===value?'●':'○'}</i><span><b>{value}</b><small>{hint}</small></span></button>)}</div></section>)}<div className="clarification-actions"><span>{Object.values(answers).filter(Boolean).length<4?'完成全部选择后生成计划':'上下文已完整，可以生成分析计划'}</span><button className="primary" onClick={submitClarifications} disabled={Object.values(answers).some(v=>!v)}>生成分析计划 →</button></div></div>}
    {task?.status==='awaiting_approval'&&<div className="gate-card approval"><div className="gate-head"><div><small>分析计划待确认</small><h2>RNA-seq 候选基因分析工作流</h2><p>共 6 步 · 预计 2 分 30 秒 · 已绑定 3 个证据来源 · 不向外部传输数据</p></div><span className="status-pill blocked">等待审批</span></div><div className="plan-preview"><span>01 校验数据结构</span><span>02 构建设计矩阵</span><span>03 执行 DESeq2</span><span>04 生成火山图</span><span>05 排序候选基因</span><span>06 撰写科研报告</span></div><div className="approval-actions"><button className="secondary" onClick={()=>setTab('evidence')}>查看证据</button><button className="primary" onClick={approvePlan}>批准并执行 →</button></div></div>}
    <div className={`canvas-wrap ${planOpen?'':'plan-collapsed'}`}><div className="canvas-toolbar"><span>分析工作流 / v1.4 <em>{connectingFrom?`正在连线：${connectingFrom} → Shift 点击目标节点`:'拖拽节点 · 拖动画布 · 滚轮缩放 · Shift+点击连线'}</em></span><div><button onClick={()=>setCanvasZoom(v=>clampZoom(v-.1))} aria-label="缩小">−</button><span>{Math.round(canvasZoom*100)}%</span><button onClick={()=>setCanvasZoom(v=>clampZoom(v+.1))} aria-label="放大">＋</button><button onClick={resetCanvas} aria-label="居中并重置">⊙</button></div></div><div className="canvas canvas-viewport" onPointerDown={startCanvasPan} onWheel={e=>{e.preventDefault();setCanvasZoom(v=>clampZoom(v+(e.deltaY<0?.08:-.08)))}}><div className="canvas-stage" style={{transform:`translate(${canvasPan.x}px,${canvasPan.y}px) scale(${canvasZoom})`}}><svg className="edges" viewBox="0 0 1000 500" preserveAspectRatio="none">{[...task.edges,...extraEdges].map(([a,b])=>{const source=task.nodes.find(n=>n.id===a)!,target=task.nodes.find(n=>n.id===b)!,s=nodePositions[a]||source,t=nodePositions[b]||target;return <line key={a+b} x1={s.x+170} y1={s.y+55} x2={t.x} y2={t.y+55} className={source.status==='succeeded'&&target.status!=='blocked'?'edge-done':'edge'} />})}</svg>{task.nodes.map(n=>{const position=nodePositions[n.id]||n;return <button key={n.id} className={`node ${n.status} ${selected===n.id?'selected':''} ${connectingFrom===n.id?'connecting':''}`} style={{left:position.x,top:position.y}} onPointerDown={e=>startNodeDrag(n,e)}><div className="node-head"><span className={`node-icon ${n.kind}`}>{n.kind==='artifact'?'▧':n.kind==='gate'?'◇':n.kind==='input'?'⇩':'◉'}</span><span className="node-status">{n.status==='succeeded'?'✓':n.status==='failed'?'!':n.status==='running'?'◌':'·'}</span></div><b>{n.label}</b><small>{n.detail}</small>{n.status==='running'&&<div className="progress"><i/></div>}{n.status==='failed'&&<span className="fix-hint">需要处理</span>}</button>})}</div></div><div className="minimap"><span/><span/><span/><span/><span/></div></div>
    <div className="conversation">{sentMessages.map((text,i)=><div className="user-message sent-message" key={`${text}-${i}`}><small>你 · 刚刚</small><p>{text}</p></div>)}{agentReplies.map((text,i)=><div className="agent-message reply-message" key={`${text}-${i}`}><div className="assistant-avatar">✦</div><div><small>BioFlow 智能体 · 刚刚</small><p>{text}</p></div></div>)}{task.status==='failed'&&<div className="message failure-message"><small>BioFlow 智能体 · 刚刚</small><p>在运行 DESeq2 前发现元数据问题：映射中缺少 <code>condition</code> 字段，4 个下游产物已暂停。</p><div className="message-actions"><button onClick={()=>{setSelected('design');setMobilePanel(true)}}>查看失败原因</button><button onClick={()=>setTab('code')}>查看生成代码</button></div></div>}<div className="composer"><span>＋</span><input value={messageText} onChange={e=>setMessageText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder="继续提问，或要求智能体修改分析参数…"/><span className="mode">标准模式⌄</span><button aria-label="发送" onClick={sendMessage}>➤</button></div></div>
   </section>
   <nav className="tool-dock" aria-label="研究工具">{[['todo','待办','☷'],['results','结果','▧'],['compute','计算','◉'],['notes','笔记','✎']].map(([key,label,icon])=><button key={key} className={tab===key&&mobilePanel?'active':''} onClick={()=>{setTab(key as typeof tab);setMobilePanel(true)}}><i>{icon}</i><span>{label}</span></button>)}</nav>
   {mobilePanel&&<button className="inspector-backdrop" aria-label="关闭检查器" onClick={()=>setMobilePanel(false)} />}<aside className={`inspector ${mobilePanel?'mobile-open':''}`}> <div className="drawer-heading"><div><small>研究工具</small><b>{{todo:'任务待办',results:'结果产物',compute:'计算资源',notes:'研究笔记',evidence:'证据依据',logs:'运行日志',code:'分析代码',structure:'3D 结构'}[tab]}</b></div><button className="close-inspector" onClick={()=>setMobilePanel(false)} aria-label="关闭工具抽屉">×</button></div><div className="inspector-tabs"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>证据</button><button className={tab==='logs'?'active':''} onClick={()=>setTab('logs')}>日志</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}>代码</button><button className={tab==='results'?'active':''} onClick={()=>setTab('results')}>结果</button><button className={tab==='structure'?'active':''} onClick={()=>setTab('structure')}>3D</button></div>{tab==='todo'&&<div className="tool-view todo-view"><div className="tool-summary"><b>分析准备</b><span>{Object.values(answers).filter(Boolean).length} / 4 已完成</span></div>{clarificationQuestions.map((q,i)=><button key={q.key} onClick={()=>{setActiveQuestion(i);setMobilePanel(false)}}><i>{answers[q.key]?'✓':'○'}</i><span><b>{q.label}</b><small>{answers[q.key]||'等待你的选择'}</small></span></button>)}</div>}{tab==='compute'&&<div className="tool-view compute-view"><div className="compute-status"><i/>计算环境待命</div><h3>标准分析环境</h3><p>4 vCPU · 16 GB 内存 · Python / R</p><dl><div><dt>运行时</dt><dd>BioFlow RNA-seq 1.4</dd></div><div><dt>数据区域</dt><dd>本地项目空间</dd></div><div><dt>外发数据</dt><dd>无</dd></div></dl></div>}{tab==='notes'&&<div className="tool-view notes-view"><textarea defaultValue="研究备注

• 比较处理组与对照组
• 优先关注 FDR < 0.05 的基因
• 输出可发表火山图与方法说明"/><small>笔记保存在当前任务上下文中</small></div>}{tab==='evidence'&&<><div className="inspector-title"><small>当前选中节点</small><h2>{node?.label}</h2><span className={`status-pill ${node?.status}`}>{node?.status?.toUpperCase()}</span></div><div className="explain-card"><span>✦ 为什么需要这一步？</span><p>This node validates the sample schema before statistical analysis. It prevents silent mis-grouping and keeps the final report reproducible.</p></div><div className="source-list"><h3>依据来源 <span>4</span></h3>{['Project metadata schema','DESeq2 Skill · v2.1','Bioconductor design guide','QC policy · 2026-08'].map((s,i)=><div className="source" key={s}><i>{i+1}</i><div><b>{s}</b><small>{i===0?'直接匹配':'语义匹配'} · 0.{91-i} 相关度</small></div><span>↗</span></div>)}</div>{node?.status==='failed'&&<div className="error-card"><b>⚠ Validation blocked</b><p>{node.error}</p><button className="primary full" onClick={retry}>{retrying?'Retrying…':'Map condition & retry'}</button></div>}</>}{tab==='logs'&&<div className="log-view"><div className="log-live"><i/> 实时事件流</div>{(liveLogs.length?liveLogs:['等待运行事件…']).map((l,i)=><p key={`${l}${i}`} className={l.includes('failed')?'log-error':''}>{l}</p>)}</div>}{tab==='code'&&<div className="code-view"><div className="code-head"><span>analysis.py</span><span className="code-state">● {running?'生成中':'就绪'}</span></div><pre><code>{codeText||`import pandas as pd\nfrom deseq2 import DESeqDataSet\n\ncounts = pd.read_csv("counts.csv")\nmetadata = pd.read_csv("sample_metadata.tsv")\n\n# Validate before execution\nassert "condition" in metadata.columns\n`}</code></pre><button className="primary full" onClick={runDemo}>{running?'代码生成中…':'运行代码'}</button></div>}{tab==='results'&&<div className="result-view"><div className="result-head"><div><small>结果产物</small><h3>火山图</h3></div><span>↧ SVG</span></div><svg className="volcano" viewBox="0 0 280 220"><line x1="32" y1="190" x2="265" y2="190"/><line x1="32" y1="20" x2="32" y2="190"/>{Array.from({length:55},(_,i)=><circle key={i} cx={45+((i*47)%205)} cy={178-((i*29)%145)} r={i%7===0?3:2} className={i%7===0?'hit':''}/>)}</svg><div className="metrics"><div><b>1,842</b><small>检测基因数</small></div><div><b>126</b><small>显著差异</small></div><div><b>18</b><small>候选基因</small></div></div><div className="lineage-card"><b>⌁ 结果血缘</b><p>counts.csv → design matrix → DESeq2 → volcano_plot.svg</p><button onClick={()=>{setSelected('de');setTab('evidence')}}>追溯到来源节点</button></div></div>}{tab==='structure'&&<div className="structure-view"><div className="structure-canvas"><div className="helix">⌁</div><span className="residue r1"/><span className="residue r2"/><span className="residue r3"/><span className="residue r4"/></div><h3>蛋白质结构预览</h3><p>3D artifact viewer is ready for a PDB/CIF result. Select a residue to bind evidence and code context.</p><button className="secondary full">在 Mol* 中打开</button></div>}<div className="vertical-splitter right" onPointerDown={e=>startResize('inspector',e)} title="拖拽调整检查器宽度"/></aside>
   <button className="mobile-inspector-trigger" onClick={()=>setMobilePanel(true)}>检查器 · {node?.label}</button>
 </main>
}
