'use client';
import { useEffect, useMemo, useState } from 'react';

type Node = { id:string; label:string; kind:string; status:string; x:number; y:number; detail:string; error?:string };
type Task = { id:string; title:string; goal:string; status:string; progress:number; nodes:Node[]; edges:string[][]; artifacts:unknown[] };
type Event = { id:number; phase:string; title:string; detail:string; state:'done'|'active'|'idle'|'error'; time:string };

const seedEvents: Event[] = [
 {id:1,phase:'01',title:'Intent detected',detail:'bulk RNA-seq · treated vs control · candidate genes',state:'done',time:'0.3s'},
 {id:2,phase:'02',title:'Query rewrite',detail:'organism=human · deliverable=publication-ready',state:'done',time:'0.5s'},
 {id:3,phase:'03',title:'Retrieval & rerank',detail:'Project files 2 · Skills 3 · Literature 12',state:'active',time:'1.2s'},
 {id:4,phase:'04',title:'Grounding plan',detail:'DESeq2 parameters bound to 4 evidence items',state:'idle',time:'—'},
];

export default function Home() {
 const [authed,setAuthed]=useState(false); const [task,setTask]=useState<Task|null>(null); const [events,setEvents]=useState(seedEvents); const [selected,setSelected]=useState('design'); const [tab,setTab]=useState<'evidence'|'logs'|'code'|'structure'>('evidence'); const [mobilePanel,setMobilePanel]=useState(false); const [running,setRunning]=useState(false); const [retrying,setRetrying]=useState(false);
 useEffect(()=>{ (async()=>{ const login=await fetch('/api/auth/login',{method:'POST'}); if(login.ok){setAuthed(true); const r=await fetch('/api/tasks'); const d=await r.json(); setTask(d.task);} })(); },[]);
 const node=useMemo(()=>task?.nodes.find(n=>n.id===selected),[task,selected]);
 const runDemo=async()=>{if(running)return; setRunning(true); await fetch('/api/runs',{method:'POST'}); setEvents(e=>e.map(x=>x.id===3?{...x,state:'done',detail:'Project files 2 · Skills 3 · Literature 12',time:'1.8s'}:x.id===4?{...x,state:'active',detail:'Parameters verified · plan ready',time:'2.1s'}:x)); setTimeout(()=>setRunning(false),1800);};
 const retry=()=>{setRetrying(true); setTimeout(()=>{setRetrying(false); setTask(t=>t?{...t,nodes:t.nodes.map(n=>n.id==='design'?{...n,status:'succeeded',detail:'condition → mapped'}:n.id==='de'?{...n,status:'running',detail:'Running DESeq2'}:n)}:t); setEvents(e=>e.map(x=>x.id===4?{...x,state:'done',detail:'Plan approved · execution resumed',time:'3.0s'}:x));},900)};
 if(!authed||!task) return <main className="boot"><div className="boot-mark">◌</div><p>Initializing secure research workspace…</p></main>;
 return <main className="app-shell">
   <aside className="rail"><div className="brand">◌</div><button className="rail-btn active">⌘<span>Workspace</span></button><button className="rail-btn">◇<span>Skills</span></button><button className="rail-btn">◈<span>Files</span></button><div className="rail-spacer"/><div className="avatar">DF</div></aside>
   <aside className="task-sidebar"><div className="project-head"><div><small>PROJECT</small><strong>BioFlow Lab</strong></div><span>⌄</span></div><div className="side-title"><span>Tasks <em>3</em></span><button>＋ New</button></div><div className="task-item selected"><i className="dot yellow"/><div><b>{task.title}</b><small>Running · 42%</small></div></div><div className="task-item"><i className="dot blue"/><div><b>Literature evidence map</b><small>Completed · 2h ago</small></div></div><div className="task-item"><i className="dot gray"/><div><b>Protein structure preview</b><small>Draft · yesterday</small></div></div><div className="side-divider"/><div className="side-title"><span>Datasets</span><button>＋ Upload</button></div><div className="dataset"><span className="file-icon">CSV</span><div><b>counts.csv</b><small>2.4 MB · 24 samples</small></div></div><div className="dataset"><span className="file-icon">TSV</span><div><b>sample_metadata.tsv</b><small>12 KB · schema checked</small></div></div><div className="sidebar-note">⌁ Cloud execution stays available when you leave this page.</div></aside>
   <section className="workspace"><header className="topbar"><div className="crumb"><span>Quick Tasks</span><b>/</b><strong>{task.title}</strong></div><div className="top-actions"><span className="live"><i/> Agent runtime 39s</span><button>Share</button><button>Layout</button></div></header>
    <div className="goal-strip"><div><small>ACTIVE RESEARCH GOAL</small><h1>{task.goal}</h1></div><div className="goal-actions"><span className="status-pill running">● RUNNING</span><button className="secondary" onClick={()=>setMobilePanel(!mobilePanel)}>Inspector</button><button className="primary" onClick={runDemo}>{running?'Running…':'Run workflow'}</button></div></div>
    <div className="evidence-strip"><div className="evidence-label"><span>✦</span><b>Evidence Pipeline</b><small>Agent decision trace</small></div>{events.map(e=><div key={e.id} className={`evidence-step ${e.state}`} onClick={()=>setTab('evidence')}><span className="phase">{e.phase}</span><div><b>{e.title}</b><small>{e.detail}</small></div><em>{e.time}</em></div>)}</div>
    <div className="canvas-wrap"><div className="canvas-toolbar"><span>WORKFLOW / v1.4</span><div><button>−</button><span>100%</span><button>＋</button><button>⊙</button></div></div><div className="canvas" style={{minWidth:900}}><svg className="edges" viewBox="0 0 1000 500" preserveAspectRatio="none">{task.edges.map(([a,b])=>{const s=task.nodes.find(n=>n.id===a)!,t=task.nodes.find(n=>n.id===b)!;return <line key={a+b} x1={s.x+170} y1={s.y+55} x2={t.x} y2={t.y+55} className={s.status==='succeeded'&&t.status!=='blocked'?'edge-done':'edge'} />})}</svg>{task.nodes.map(n=><button key={n.id} className={`node ${n.status} ${selected===n.id?'selected':''}`} style={{left:n.x,top:n.y}} onClick={()=>{setSelected(n.id);setMobilePanel(true)}}><div className="node-head"><span className={`node-icon ${n.kind}`}>{n.kind==='artifact'?'▧':n.kind==='gate'?'◇':n.kind==='input'?'⇩':'◉'}</span><span className="node-status">{n.status==='succeeded'?'✓':n.status==='failed'?'!':n.status==='running'?'◌':'·'}</span></div><b>{n.label}</b><small>{n.detail}</small>{n.status==='running'&&<div className="progress"><i/></div>}{n.status==='failed'&&<span className="fix-hint">Needs attention</span>}</button>)}</div><div className="minimap"><span/><span/><span/><span/><span/></div></div>
    <div className="conversation"><div className="assistant-avatar">✦</div><div className="message"><small>BIOMNI AGENT · JUST NOW</small><p>I found a metadata issue before running DESeq2. The <code>condition</code> column is missing from the mapping, so 4 downstream artifacts are blocked.</p><div className="message-actions"><button onClick={()=>setSelected('design')}>Explain this step</button><button onClick={()=>setTab('code')}>View generated code</button></div></div><div className="composer"><span>＋</span><input placeholder="Ask about this workflow or change a parameter…"/><span className="mode">Standard⌄</span><button>➤</button></div></div>
   </section>
   <aside className={`inspector ${mobilePanel?'mobile-open':''}`}><div className="inspector-tabs"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>Evidence</button><button className={tab==='logs'?'active':''} onClick={()=>setTab('logs')}>Logs</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}>Code</button><button className={tab==='structure'?'active':''} onClick={()=>setTab('structure')}>3D</button><button className="close-inspector" onClick={()=>setMobilePanel(false)}>×</button></div>{tab==='evidence'&&<><div className="inspector-title"><small>SELECTED NODE</small><h2>{node?.label}</h2><span className={`status-pill ${node?.status}`}>{node?.status?.toUpperCase()}</span></div><div className="explain-card"><span>✦ Why this step?</span><p>This node validates the sample schema before statistical analysis. It prevents silent mis-grouping and keeps the final report reproducible.</p></div><div className="source-list"><h3>Grounding sources <span>4</span></h3>{['Project metadata schema','DESeq2 Skill · v2.1','Bioconductor design guide','QC policy · 2026-08'].map((s,i)=><div className="source" key={s}><i>{i+1}</i><div><b>{s}</b><small>{i===0?'Direct match':'Semantic match'} · 0.{91-i} relevance</small></div><span>↗</span></div>)}</div>{node?.status==='failed'&&<div className="error-card"><b>⚠ Validation blocked</b><p>{node.error}</p><button className="primary full" onClick={retry}>{retrying?'Retrying…':'Map condition & retry'}</button></div>}</>}{tab==='logs'&&<div className="log-view"><div className="log-live"><i/> Live event stream</div>{['[39.1s] runner: validating schema','[39.4s] retriever: 4 evidence items bound','[40.0s] design_matrix: missing condition','[40.0s] run paused · awaiting input'].map((l,i)=><p key={l} className={i===2?'log-error':''}>{l}</p>)}</div>}{tab==='code'&&<div className="code-view"><div className="code-head"><span>analysis.py</span><span className="code-state">● {running?'GENERATING':'READY'}</span></div><pre><code>{`import pandas as pd\nfrom deseq2 import DESeqDataSet\n\ncounts = pd.read_csv("counts.csv")\nmetadata = pd.read_csv("sample_metadata.tsv")\n\n# Validate before execution\nassert "condition" in metadata.columns\n`}</code></pre><button className="primary full" onClick={()=>setRunning(true)}>Run code</button></div>}{tab==='structure'&&<div className="structure-view"><div className="structure-canvas"><div className="helix">⌁</div><span className="residue r1"/><span className="residue r2"/><span className="residue r3"/><span className="residue r4"/></div><h3>Protein structure preview</h3><p>3D artifact viewer is ready for a PDB/CIF result. Select a residue to bind evidence and code context.</p><button className="secondary full">Open Mol* viewer</button></div>}</aside>
   <button className="mobile-inspector-trigger" onClick={()=>setMobilePanel(true)}>Inspector · {node?.label}</button>
 </main>
}
