export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiRequestContract = {
  headers: string;
  path: string;
  query: string;
  body: string;
};

export type ApiEndpoint = {
  id: string;
  method: ApiMethod;
  path: string;
  summary: string;
  access: string;
  request: ApiRequestContract;
  response: string;
  statusCodes: string;
  persistence: string;
};

export type ApiGroup = {
  id: string;
  title: string;
  summary: string;
  endpoints: ApiEndpoint[];
};

const bearerHeaders = "Authorization: Bearer <accessToken>；Accept: application/json";
const writeHeaders = `${bearerHeaders}；Content-Type: application/json；Origin: same-origin`;
const publicWriteHeaders = "Content-Type: application/json；Origin: same-origin";
const sseHeaders =
  "Authorization: Bearer <accessToken>；Accept: text/event-stream；Cache-Control: no-cache";
const uploadHeaders =
  "Authorization: Bearer <accessToken>；multipart/form-data（由浏览器生成 boundary）；Origin: same-origin";

function requestContract(
  headers: string,
  detail: Partial<Omit<ApiRequestContract, "headers">> = {},
): ApiRequestContract {
  return {
    headers,
    path: "无",
    query: "无",
    body: "无",
    ...detail,
  };
}

function endpoint(
  method: ApiMethod,
  path: string,
  summary: string,
  access: string,
  request: ApiRequestContract,
  response: string,
  statusCodes: string,
  persistence: string,
): ApiEndpoint {
  return {
    id: `${method}-${path}`,
    method,
    path,
    summary,
    access,
    request,
    response,
    statusCodes,
    persistence,
  };
}

export const apiGroups: ApiGroup[] = [
  {
    id: "api-auth",
    title: "1. 鉴权与用户",
    summary: "Bearer 会话、三角色登录和管理员用户权限闭环。",
    endpoints: [
      endpoint(
        "POST",
        "/api/auth/login",
        "校验账号、密码、角色和请求来源，签发短期访问令牌。",
        "公开接口；写请求同源校验。",
        requestContract(publicWriteHeaders, {
          body: "username:string；password:string；role: researcher | reviewer | admin",
        }),
        "authenticated:boolean；accessToken:string；expiresAt:number；user:SessionUser",
        "200；400 INVALID_ROLE；401 WRONG_PASSWORD；403 ACCOUNT_DISABLED / ROLE_MISMATCH；404 ACCOUNT_NOT_FOUND",
        "读取 auth-users.json；生产映射 users、roles、user_permissions、access_sessions。",
      ),
      endpoint(
        "GET",
        "/api/auth/session",
        "验证令牌签名、有效期和当前用户状态并恢复会话。",
        "有效 Bearer Token。",
        requestContract(bearerHeaders),
        "authenticated:true；accessToken；expiresAt；user:SessionUser",
        "200；401",
        "重新读取 auth-users.json；用户停用或角色变化后旧令牌失效。",
      ),
      endpoint(
        "POST",
        "/api/auth/logout",
        "确认当前会话有效，由前端清除 sessionStorage 令牌。",
        "已登录；写请求同源校验。",
        requestContract(writeHeaders),
        "ok:true",
        "200；401；403",
        "本地版不保存服务端 Session；生产可写 access_sessions.revoked_at。",
      ),
      endpoint(
        "GET",
        "/api/admin/users",
        "读取脱敏用户、角色和原子权限列表。",
        "users:manage。",
        requestContract(bearerHeaders),
        "users: ManagedUser[]；不返回密码哈希与盐。",
        "200；401；403",
        "读取 auth-users.json；生产映射 users、roles、permissions。",
      ),
      endpoint(
        "POST",
        "/api/admin/users",
        "创建用户并分配角色、权限和启用状态。",
        "users:manage；写请求同源校验。",
        requestContract(writeHeaders, {
          body: "username；password(8..128)；name；role；permissions?:string[]；enabled?:boolean",
        }),
        "201；user:ManagedUser；users:ManagedUser[]",
        "201；400；401；403",
        "随机盐 + scrypt 哈希写入 auth-users.json；生产映射 users 与权限关系表。",
      ),
      endpoint(
        "PATCH",
        "/api/admin/users",
        "更新用户名称、角色、权限、密码或启用状态。",
        "users:manage；写请求同源校验。",
        requestContract(writeHeaders, {
          body: "id:string 必填；name / role / permissions / enabled / password 均可选",
        }),
        "user:ManagedUser；users:ManagedUser[]",
        "200；400；401；403；409",
        "更新 auth-users.json；角色或状态改变会使不匹配的旧令牌失效。",
      ),
    ],
  },
  {
    id: "api-project-task",
    title: "2. 项目、任务与对话",
    summary: "项目目录、任务状态机、澄清、审批、消息与研究笔记。",
    endpoints: [
      endpoint(
        "GET",
        "/api/projects",
        "读取当前用户可见的项目目录。",
        "tasks:read。",
        requestContract(bearerHeaders),
        "projects: WorkspaceProject[]",
        "200；401",
        "读取 projects.json；生产映射 projects、project_members。",
      ),
      endpoint(
        "POST",
        "/api/projects",
        "新建项目并返回更新后的项目列表。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { body: "name:string，规范化后 2..48 字符且不可重名" }),
        "201；project:WorkspaceProject；projects:WorkspaceProject[]",
        "201；400；401；403",
        "原子写入 projects.json；生产映射 projects。",
      ),
      endpoint(
        "DELETE",
        "/api/projects",
        "删除非保护项目目录。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { query: "id:string 必填" }),
        "project:WorkspaceProject；projects:WorkspaceProject[]",
        "200；400；401；403；409",
        "删除 projects.json 中的目录记录；生产由 tasks.project_id 外键处理级联。",
      ),
      endpoint(
        "GET",
        "/api/tasks",
        "读取默认任务快照与任务队列。",
        "已登录。",
        requestContract(bearerHeaders),
        "task:ResearchTask；tasks:TaskListItem[]",
        "200；401",
        "读取 data/state.json。",
      ),
      endpoint(
        "POST",
        "/api/tasks",
        "创建真实或演示任务并绑定技能与文件。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, {
          body: "title:string；skillId?:string；fileIds?:string[]；executionMode?: real | demo",
        }),
        "task:ResearchTask；tasks:TaskListItem[]",
        "200；400；401；403；404",
        "任务与技能快照写入 data/state.json；生产映射 tasks、task_skills、task_files。",
      ),
      endpoint(
        "GET",
        "/api/tasks/:taskId",
        "读取指定任务、节点、文件、运行与产物快照。",
        "已登录。",
        requestContract(bearerHeaders, { path: "taskId:string" }),
        "task:ResearchTask；tasks:TaskListItem[]",
        "200；401；404",
        "读取 data/state.json；生产映射 tasks 及其关联实体。",
      ),
      endpoint(
        "DELETE",
        "/api/tasks/:taskId",
        "删除非保护、非运行中的任务及关联状态。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "taskId:string" }),
        "deletedTaskId:string；tasks:TaskListItem[]",
        "200；401；403；404；409",
        "清理任务、对话、笔记、布局、运行映射和关联状态。",
      ),
      endpoint(
        "POST",
        "/api/tasks/:taskId/clarifications",
        "提交数据格式、比较方案、物种和交付物。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, {
          path: "taskId:string",
          body: "answers:{ format；comparison；organism；deliverable }，四项均不可为空",
        }),
        "task:ResearchTask",
        "200；400；401；403；404",
        "写入任务 clarification；生产映射 tasks.clarification jsonb。",
      ),
      endpoint(
        "POST",
        "/api/tasks/:taskId/approve",
        "批准已生成计划并解除运行阻塞。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "taskId:string" }),
        "task:ResearchTask",
        "200；401；403；404；409",
        "更新任务审批与状态字段；生产映射 tasks 与 audit_logs。",
      ),
      endpoint(
        "GET",
        "/api/tasks/:taskId/conversation",
        "读取任务级连续对话。",
        "已登录。",
        requestContract(bearerHeaders, { path: "taskId:string" }),
        "messages:ConversationMessage[]",
        "200；401；404",
        "读取 data/state.json.conversations[taskId]；生产映射 conversation_messages。",
      ),
      endpoint(
        "PUT",
        "/api/tasks/:taskId/conversation",
        "保存最多 100 条任务消息及其 Trace、引用和反馈。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, {
          path: "taskId:string",
          body: "messages:ConversationMessage[]，最多 100 条",
        }),
        "messages:ConversationMessage[]",
        "200；400；401；403；404",
        "写入 data/state.json.conversations；生产映射 conversation_messages。",
      ),
      endpoint(
        "GET",
        "/api/tasks/:taskId/notes",
        "读取研究笔记或审阅意见。",
        "已登录。",
        requestContract(bearerHeaders, { path: "taskId:string" }),
        "notes:string",
        "200；401；404",
        "读取 data/state.json.notesByTaskId；生产可映射 task_notes。",
      ),
      endpoint(
        "PUT",
        "/api/tasks/:taskId/notes",
        "保存研究笔记或审阅意见。",
        "reviews:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "taskId:string", body: "notes:string" }),
        "notes:string",
        "200；400；401；403；404",
        "写入 data/state.json.notesByTaskId；生产可映射 task_notes / reviews。",
      ),
    ],
  },
  {
    id: "api-files",
    title: "3. 文件、解析与原件",
    summary: "上传、策略解析、正文预览、重新索引、下载和安全删除。",
    endpoints: [
      endpoint(
        "GET",
        "/api/files",
        "读取 Research Worker 中的真实文档目录。",
        "files:read。",
        requestContract(bearerHeaders),
        "items:ProjectFileRecord[]；total；page；pageSize；source；updatedAt",
        "200；401；503",
        "读取 Worker SQLite document 记录；原件保存在 objects/。",
      ),
      endpoint(
        "POST",
        "/api/files/profile",
        "上传文件并执行格式路由、解析、清洗、分块与索引。",
        "files:write；写请求同源校验。",
        requestContract(uploadHeaders, {
          query: "taskId:string 必填",
          body: "multipart 字段 file；CSV/TSV/TXT/MD/XLSX/PDF/DOCX/PNG/JPG；1B..300MB",
        }),
        "profile:DataFileProfile；document:ResearchDocument；task:ResearchTask",
        "200；400；401；403；404；422；503",
        "写入 objects/、SQLite 文档记录、Qdrant 索引和任务文件绑定。",
      ),
      endpoint(
        "GET",
        "/api/files/:fileId",
        "读取受限正文、表格、实际解析器和索引状态。",
        "files:read。",
        requestContract(bearerHeaders, { path: "fileId:string" }),
        "ResearchDocument；最多 50 个 section，每段正文最多 10,000 字符",
        "200；401；404；503",
        "读取 SQLite 文档 JSON；不暴露内部对象路径和原始 chunks。",
      ),
      endpoint(
        "DELETE",
        "/api/files/:fileId",
        "删除文档记录、向量、原件和任务绑定。",
        "files:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "fileId:string" }),
        "deletedFileId；deletedName；affectedTaskIds:string[]",
        "200；401；403；404；409；503",
        "同步清理 SQLite、Qdrant points、objects/ 原件与任务 fileIds/dataProfiles。",
      ),
      endpoint(
        "GET",
        "/api/files/:fileId/original",
        "鉴权后内联预览或下载原始二进制文件。",
        "files:read。",
        requestContract(bearerHeaders, {
          path: "fileId:string",
          query: "download?:1；存在时 attachment，否则 inline",
        }),
        "原始二进制流；Content-Type、UTF-8 文件名、nosniff、no-store",
        "200；401；404；503",
        "读取受管理 objects/<content-id>.<ext>。",
      ),
      endpoint(
        "POST",
        "/api/files/:fileId/reparse",
        "重新执行原件解析并异步重建向量索引。",
        "files:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "fileId:string" }),
        "file:ProjectFileRecord",
        "200；401；403；404；503",
        "更新 SQLite 解析状态并重建 Qdrant points。",
      ),
    ],
  },
  {
    id: "api-rag",
    title: "4. RAG 检索与审计",
    summary: "任务文件范围内的混合检索、Trace、分阶段结果和事件读取。",
    endpoints: [
      endpoint(
        "GET",
        "/api/rag/query",
        "读取当前保存的 RAG Trace 历史。",
        "已登录。",
        requestContract(bearerHeaders),
        "traces:RagTrace[]",
        "200；401",
        "读取 data/state.json.ragTraces；生产映射 rag_traces。",
      ),
      endpoint(
        "POST",
        "/api/rag/query",
        "在当前任务文件范围内执行 Qdrant + BM25 + RRF；对话场景可追加真实 LLM 答复。",
        "runs:execute；写请求同源校验。",
        requestContract(writeHeaders, {
          query: "taskId:string 必填",
          body: "query:string(1..2000)；mode:快速模式 | 标准模式 | 深度研究；includeAnswer?:boolean",
        }),
        "trace:RagTrace；includeAnswer=true 时额外返回 answer:{content,provider,model}",
        "200；400；401；403；404；409；422；502",
        "保存完整 Trace、来源、分数、模式和 reasoning effort；模型仅读取证据摘要，不持久化密钥。",
      ),
      endpoint(
        "GET",
        "/api/rag/traces/:traceId",
        "读取完整 Trace、来源、分数和最终决策。",
        "已登录。",
        requestContract(bearerHeaders, { path: "traceId:string" }),
        "trace:RagTrace",
        "200；401；404",
        "读取任务级 ragTraces；生产映射 rag_traces 与 rag_trace_items。",
      ),
      endpoint(
        "GET",
        "/api/rag/traces/:traceId/:stage",
        "按阶段读取文档、分块、召回、精排、图谱、grounding 或工具记录。",
        "已登录。",
        requestContract(bearerHeaders, {
          path: "traceId:string；stage: documents | chunks | retrieval | rerank | graph | grounding | tools",
        }),
        "traceId；stage；data:unknown[]",
        "200；401；404",
        "读取已持久化 Trace 中的指定阶段。",
      ),
      endpoint(
        "GET",
        "/api/rag/traces/:traceId/events",
        "以一次性 SSE 发送已完成 Trace 和 completed 事件。",
        "已登录。",
        requestContract(sseHeaders, { path: "traceId:string" }),
        "text/event-stream：trace -> completed -> close",
        "200；401；404",
        "只读已完成 Trace；实时计划与计算使用独立 SSE 接口。",
      ),
    ],
  },
  {
    id: "api-plan",
    title: "5. Agent 计划与 SSE",
    summary: "真实模型计划、等待心跳、失败定位和任务持久化。",
    endpoints: [
      endpoint(
        "POST",
        "/api/agent/plan",
        "生成可审批计划；按 Accept 返回 JSON 或逐步 SSE。",
        "runs:execute；写请求同源校验。",
        requestContract(
          "Authorization: Bearer <accessToken>；Content-Type: application/json；Accept: application/json 或 text/event-stream；Origin: same-origin",
          {
            body: "taskId；query；clarification；evidence[]；mode（映射 low / medium / high reasoning effort）",
          },
        ),
        "JSON: plan + task；SSE: plan.started / worker.* / llm.* / plan.waiting / persisting / completed | failed",
        "流建立前 400/401/403/404；JSON 上游错误 500/502；流内错误通过 plan.failed",
        "成功计划写入当前任务；模型密钥只由 Next/Worker 服务端读取。",
      ),
    ],
  },
  {
    id: "api-runs",
    title: "6. 运行、SSE 与真实计算",
    summary: "运行实例、断线恢复、节点重试、PyDESeq2 作业与产物下载。",
    endpoints: [
      endpoint(
        "POST",
        "/api/runs",
        "创建稳定演示 Runner 的工作流运行。",
        "runs:execute；写请求同源校验。",
        requestContract(writeHeaders, { query: "taskId:string 必填" }),
        "runId:string；task:ResearchTask",
        "200；401；403；404；409",
        "运行、节点状态和首批事件写入 data/state.json。",
      ),
      endpoint(
        "GET",
        "/api/runs/:runId/events",
        "持续推送运行事件并支持断线续传。",
        "已登录。",
        requestContract(sseHeaders, {
          path: "runId:string",
          query: "after?:eventId；也支持 Last-Event-ID Header",
        }),
        "持续 text/event-stream；事件按 id 单调递增",
        "200；401",
        "按 runId + event id 读取事件；生产映射 run_events(run_id, sequence_no)。",
      ),
      endpoint(
        "POST",
        "/api/runs/:runId/cancel",
        "取消当前运行并追加取消事件。",
        "runs:execute；写请求同源校验。",
        requestContract(writeHeaders, { path: "runId:string" }),
        "ok:true 或当前运行状态",
        "200；401；403；404",
        "更新运行与任务状态并追加 run event。",
      ),
      endpoint(
        "POST",
        "/api/runs/:runId/nodes/:nodeId/retry",
        "重试失败节点并恢复其下游状态。",
        "runs:execute；写请求同源校验。",
        requestContract(writeHeaders, { path: "runId:string；nodeId:string" }),
        "task:ResearchTask 或节点状态结果",
        "200；400；401；403；404",
        "恢复节点和下游状态，并追加 retry 事件。",
      ),
      endpoint(
        "GET",
        "/api/tasks/:taskId/analysis",
        "查询 PyDESeq2 作业，或通过参数切换为实时 SSE。",
        "已登录。",
        requestContract(bearerHeaders, {
          path: "taskId:string",
          query: "stream?:1；jobId?:string；SSE 时 Accept:text/event-stream",
        }),
        "JSON: job:AnalysisJob|null + task；SSE: connected / queued / running / waiting / completed / failed / cancelled",
        "200；401；404；409；503",
        "读取 Worker SQLite 作业；任务保存 analysisJobId。",
      ),
      endpoint(
        "POST",
        "/api/tasks/:taskId/analysis",
        "载入练习数据、取消作业或提交真实 PyDESeq2 计算。",
        "runs:execute；写请求同源校验。",
        requestContract(writeHeaders, {
          path: "taskId:string",
          body: "action?:samples|cancel；或 countsId、metadataId、condition、control、treated、batch?、alpha?",
        }),
        "samples:task；run/cancel: job:AnalysisJob + task",
        "200；400；401；403；404；409；422；503",
        "提交/更新 SQLite 作业队列，绑定任务文件并写入作业状态。",
      ),
      endpoint(
        "GET",
        "/api/tasks/:taskId/analysis/:name",
        "下载真实计算生成的结果、图、报告或分析脚本。",
        "已登录。",
        requestContract(bearerHeaders, {
          path: "taskId:string；name: results.csv | volcano.png | report.md | analysis.py",
        }),
        "鉴权二进制流；火山图为 image/png",
        "200；401；404；409；503",
        "读取 jobs/<jobId>/<artifact>；生产映射 artifacts.object_key。",
      ),
    ],
  },
  {
    id: "api-skill-layout",
    title: "7. 技能、布局与结构",
    summary: "技能目录、声明式配置、画布版本和蛋白结构 Adapter。",
    endpoints: [
      endpoint(
        "GET",
        "/api/skills",
        "搜索、筛选并分页读取技能目录。",
        "skills:read。",
        requestContract(bearerHeaders, {
          query: "search；source；category；availability；page；pageSize",
        }),
        "items:SkillRecord[]；total；page；pageSize",
        "200；401",
        "合并种子目录与 data/catalog-state.json；生产映射 skills。",
      ),
      endpoint(
        "POST",
        "/api/skills",
        "创建只保存配置、不执行用户代码的声明式技能。",
        "skills:write；写请求同源校验。",
        requestContract(writeHeaders, {
          body: "name；category；description；source?；version?；inputs；outputs；instructions",
        }),
        "201；skill:SkillRecord",
        "201；400；401；403",
        "写入 data/catalog-state.json；生产映射 skills 与 skill_versions。",
      ),
      endpoint(
        "GET",
        "/api/skills/:skillId",
        "读取技能契约、输入输出和运行边界。",
        "skills:read。",
        requestContract(bearerHeaders, { path: "skillId:string" }),
        "skill:SkillRecord",
        "200；401；404",
        "读取种子目录或 data/catalog-state.json。",
      ),
      endpoint(
        "PATCH",
        "/api/skills/:skillId",
        "启用或停用技能。",
        "skills:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "skillId:string", body: "enabled:boolean" }),
        "skill:SkillRecord",
        "200；400；401；403；404",
        "更新 data/catalog-state.json；生产映射 skills.enabled。",
      ),
      endpoint(
        "DELETE",
        "/api/skills/:skillId",
        "删除自建技能，或从当前工作区能力目录移除预置/共享技能。",
        "skills:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "skillId:string" }),
        "deletedSkillId:string；disposition: deleted | removed",
        "200；401；403；404",
        "自建技能从 data/catalog-state.json.customSkills 删除；预置技能写入 removedSkillIds。生产映射 workspace_skill_catalog。",
      ),
      endpoint(
        "GET",
        "/api/workflows/:workflowId/layout",
        "读取当前任务的画布位置、缩放、平移与版本。",
        "tasks:read。",
        requestContract(bearerHeaders, {
          path: "workflowId:string",
          query: "taskId:string 必填",
        }),
        "layout:WorkflowLayoutState",
        "200；401；404",
        "读取 data/state.json.workflowLayouts[taskId]；生产映射 workflow_layouts。",
      ),
      endpoint(
        "PUT",
        "/api/workflows/:workflowId/layout",
        "自动保存当前画布布局并校验 revision。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, {
          path: "workflowId:string",
          query: "taskId:string 必填",
          body: "nodePositions；extraEdges；zoom；pan；revision",
        }),
        "layout:WorkflowLayoutState",
        "200；400；401；403；404；409",
        "更新任务当前布局；生产映射 workflow_layouts.current_revision。",
      ),
      endpoint(
        "POST",
        "/api/workflows/:workflowId/layout",
        "创建命名画布版本用于复盘与演示。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, {
          path: "workflowId:string",
          query: "taskId:string 必填",
          body: "name；nodePositions；extraEdges；zoom；pan；revision",
        }),
        "layout:WorkflowLayoutState；version:WorkflowLayoutVersion",
        "200；400；401；403；404；409",
        "追加布局版本；生产映射 workflow_layout_versions。",
      ),
      endpoint(
        "POST",
        "/api/workflows/:workflowId/approve",
        "兼容旧演示入口的工作流审批。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { path: "workflowId:string" }),
        "task:ResearchTask|null",
        "200；401；403；404",
        "内部更新默认任务；新代码应优先调用任务级 approve 接口。",
      ),
      endpoint(
        "GET",
        "/api/structures/:accession",
        "读取 PDB/CIF 结构 Adapter 状态、坐标或降级信息。",
        "已登录。",
        requestContract(bearerHeaders, {
          path: "accession:string",
          query: "format?: pdb | cif",
        }),
        "结构来源、格式、坐标内容或明确的 Adapter 降级状态",
        "200；400；401；404",
        "当前读取本地 PDB fixture；生产可连接结构对象存储或外部数据库。",
      ),
    ],
  },
  {
    id: "api-diagnostics",
    title: "8. 演示、诊断与交付文档",
    summary: "受控演示配置、开发环境清理、OpenAPI、接口规范和数据库 DDL。",
    endpoints: [
      endpoint(
        "GET",
        "/api/demo/config",
        "读取演示运行参数。",
        "已登录。",
        requestContract(bearerHeaders),
        "config:DemoConfig",
        "200；401",
        "读取 data/state.json.config。",
      ),
      endpoint(
        "POST",
        "/api/demo/config",
        "保存规范化后的演示运行参数。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders, { body: "DemoConfig 可写字段" }),
        "config:DemoConfig",
        "200；400；401；403",
        "写入 data/state.json.config。",
      ),
      endpoint(
        "POST",
        "/api/demo/reset",
        "仅开发环境重置演示任务。",
        "tasks:write；写请求同源校验。",
        requestContract(writeHeaders),
        "task:ResearchTask",
        "200；401；403；404",
        "重建受控演示任务状态，不影响用户上传原件。",
      ),
      endpoint(
        "POST",
        "/api/demo/cleanup",
        "仅开发环境清理集成测试夹具。",
        "users:manage；写请求同源校验。",
        requestContract(writeHeaders),
        "清理统计对象",
        "200；401；403；404",
        "删除带测试标识的任务、文件和关联状态。",
      ),
      endpoint(
        "GET",
        "/api/research/openapi",
        "下载 Research Service 的 FastAPI OpenAPI。",
        "已登录。",
        requestContract(bearerHeaders),
        "application/json 下载流",
        "200；401；503",
        "实时代理 Worker openapi.json，不写入业务数据。",
      ),
      endpoint(
        "GET",
        "/api/docs/:document",
        "在线查看或下载 API Markdown 与 PostgreSQL DDL。",
        "tasks:read。",
        requestContract(bearerHeaders, {
          path: "document: api-contract | database-ddl",
          query: "download?:1；存在时 attachment，否则 inline",
        }),
        "UTF-8 Markdown 或 SQL 文本流",
        "200；401；404；503",
        "读取仓库 docs/API接口规范.md 或 docs/数据库设计.sql。",
      ),
    ],
  },
];
